### ISSUE TITLE
maven-metadata.xml doesn't exist (for kodein-framework-android)

### ISSUE THREAD

**Issue by dutchmo** [SalomonBrys/Kodein#108]
The android component is not resolving in gradle and I don't see the metadata at http://dl.bintray.com/salomonbrys/kodein/org/kodein/kodein-framework-android/

Also i see you've gone to beta2 so might want to update dep in doc at https://salomonbrys.github.io/Kodein/?5.0/android

**Comment by SalomonBrys** [comment]
Wow, you were quick ;)

The documentation has been updated.

Also, there was a problem in the upload on the upload of kodein-framework-android-5.0.0-beta2.aar. I've re-uploaded it ;)

Due to me being stupid, the 5.0-beta1 was not a maven upload, but an artifact upload, which did not generate maven metadata or pom files.
It is corrected in beta2 ;)
