### ISSUE TITLE
Support for custome scopes

### ISSUE THREAD

**Issue by pawelByszewski** [SalomonBrys/Kodein#13]
Please add support for custome scopes. Now there is possibility to implement custome scope but ot would be nice to have some generic mechanism to use scopes just by define some scope identifier.

**Comment by SalomonBrys** [comment]
You can already define custom scopes.

Do you have anything in mind to make that easier ?

**Comment by pawelByszewski** [comment]
As far as I know I cannot define custome scope, I have to implement it. I have already implement some proof of concept. I will show it to you at the beginning of next week

**Comment by SalomonBrys** [comment]
Looking forward to it :)

**Comment by pawelByszewski** [comment]
please checkout gist
https://gist.github.com/pawelByszewski/af4946ed71cbdfea45db
it is just to shows my intentions. In that way you can define point whe scope starts and ends - for example bind it with Activity life cycle.

**Comment by SalomonBrys** [comment]
I see,
I'm working on something a little bit more advanced, thanks for the idea, I'll show it here for feedback ;)

**Comment by SalomonBrys** [comment]
Everything I describe here is part of `2.7.0-beta1` which I deployed on Maven, I'd be greatful to anyone who would test and give feedback ;)

As you may know, Kodein allows to register factories : that is a function `(A) -> F`. You usually register it that way :

```
bind<Person>() with factory { name: String -> Person(name) }
```

Now, let's consider a *scoped singleton*. I call *scoped singleton* an object that should be singleton inside a specified scope, whether that scope is temporal (there should be only one instance during that time) or contextualized (there should be only one instance for this activity / request / etc.).

Here is the usage code for the new `scopedSingleton` in Kodein with the `activityScope` in Kodein-Android:

```
bind<Person>() with scopedSingleton(::activityScope) { Person() }
```

And later:

```
val person = kodein.factory<Activity, Person>().invoke(getActivity())
```

The `scopedSingleton` actually registers a factory that assigns a singleton to an object that will represent the scope. For one activity, it will always give the same binded object.  
In the example above, you could ask multiple times a Person factory, this factory will always give the same Person when you provide the same Activity as argument.

In fact, you can personalize the object for the scope because it is the argument passed to the factory method:

```
bind<Person>() with scopedSingleton(::activityScope) { Person(it.getStringExtra("name")) }
```

Note that because, the activityScope uses a WeakHashMap, there's no need to "clear" the scope.


Now, factories are a bit cumbersome, so there's another generic scope: `autoScopedSingleton`. Here's how it works for Android:

```
bind<Person>() with autoScopedSingleton(::activityScope) { Person(it.getStringExtra("name")) }
```

And later:

```
val person = kodein.instance<Person>()
```

The catch is that, in your `Application` class, you must do this :

```
registerActivityLifecycleCallbacks(ActivityScopeLifecycleManager)
```

Thanks to the `ActivityScopeLifecycleManager`, Kodein will always know the last activity opened, and get the object that is scoped for the current activity. Note that this works with the back stack (once an activity finished, the previous activity re-becomes the current scope).


------------------------------------------


Now for the internal parts, what if you want to create your own scopes.

Well, `scopedSingleton` takes a `(A) -> HashMap<Any, Any>` parameter, meaning that you need a function that will give a `HashMap<Any, Any>` according to your scope object.  
Here's an example for a scope by String name:

```
private val _globalScope = HashMap<String, HashMap<Any, Any>>()
fun globalScope(scope: String) = synchronized(_globalScope) { _globalScope.getOrPut(scope) { HashMap() } }
fun clearGlobalScope(scope: String) = _globalScope.remove(scope)
```

With that, you can:

```
bind<Person>() with scopedSingleton(::globalScope) { Person(it) } // Note that it creates a Person with the scope name ;)
```


`autoScopedSingleton` works the same way, but it taked a `() -> HashMap<Any, Any>` parameter, meaning that there is no argument. You can either return *always* the same map, or you can return a different map according to a global context.

Finally, here's the code that mimmicks what you proposed in your gist:

```
private val _globalScope = HashMap<Any, Any>()
fun globalScope() = _globalScope
fun clearGlobalScope() = _globalScope.clear()
```

And simply:

```
bind<Person>() with autoScopedSingleton(::globalScope) { Person() }
```


------------------------------------------


Thank you for reading this far. I hope this willfit your usecases. Please let me know any feedback you might have.

Once again : this is testable with the version `2.7.0-beta1`

**Comment by pawelByszewski** [comment]
Sorry for so long period of silence.  It looks really great and I will test it in next week. Have you published it as a Snapshoot anywhere?

**Comment by SalomonBrys** [comment]
It's [in maven central](https://search.maven.org/#artifactdetails%7Ccom.github.salomonbrys.kodein%7Ckodein%7C2.7.0-beta1%7Cjar) :)

**Comment by pawelByszewski** [comment]
I am always getting 
There are no current activity. This can either mean that you forgot to register the ActivityScopeLifecycleManager
In a few minutes I will publish a sample.

**Comment by SalomonBrys** [comment]
Thanks ;)
I'll write the documentation and publish next week.

**Comment by SalomonBrys** [comment]
Version `2.7.0-beta2` slightly changes this behaviour.
Furthermore, [the documentation for this feature](https://github.com/SalomonBrys/Kodein/tree/v2.7.0-beta#create-your-own-scopes) has been written :)

**Comment by SalomonBrys** [comment]
version `2.7.0` has been published
