### ISSUE TITLE
Type inference failed using KodeinGlobalAware or KodeinAware but not with KodeinInjected

### ISSUE THREAD

**Issue by lalunamel** [SalomonBrys/Kodein#57]
Hi!

I'd like to use KodeinGlobalAware in my Android application as described [here](https://salomonbrys.github.io/Kodein/#_being_globally_aware) (though the docs differ from the actual implementation required). I feel it's use case fits perfectly for my situation.

When I create a class:
```
class MyClass : KodeinGlobalAware {
   val garfield : Cat by with("I hate Mondays").instance()
}
```

the compiler gives me an error on `instance()`
```
Type inference failed: Not enough information to infer parameter T in
  inline fun<reified T: Any> CurriedKodeinFactory<*>.instance(tag : Any? =...) : T
Please specify it explicitly
```

This error does not occur when I make the class `KodeinInjected`

The binding for this class I'd like to inject looks like
`bind<Cat>() with factory { catchphrase: String -> Cat(catchphrase) }`

I've tried passing type information to `instance()` with `instance<Cat>()` but that only produces another, different error 
```
missing 'getValue(Cat, KProperty<*>)' method on delegate of type 'Cat'
```

This behavior also happens when using `KodeinAware` instead of `KodeinGlobalAware`.
What gives?

**Comment by SalomonBrys** [comment]
I really need to emphasis this in the doc as you are not the first one to report this issue ;)

`KodeinInjected` and `KodeinAware` work very differently.

By its nature, `KodeinInjected` can only access injected dependencies once it is injected, this means that it uses [Kotlin's delegated properties](https://kotlinlang.org/docs/reference/delegated-properties.html) to access said dependencies only once it has been injected, hence the use of `by`.

`KodeinAware` and `KodeinGlobalAware`, on the other hand, have direct access to a `Kodein` instance. Therefore, they *do not use delegated properties*.

This means that your example will work simply by using `=` instead of `by`:

```
class MyClass : KodeinGlobalAware {
   val garfield : Cat = with("I hate Mondays").instance()
}
```

Really sorry that this was not clear enough in the documentation, I'll update it.

Can you be more specific about what you mean when you say "though the docs differ from the actual implementation required" ? I'm not a natural born documentation writer, I'd be greatful for any advice ;)

Salomon.

**Comment by lalunamel** [comment]
Hello, apologies for the delay!
Phew, it was a while ago! 

What I think I meant was that the docs have a snippet of code describing how to add a module to the global kodein instance: `kodein.global.addModule(dbModule)`

and I needed to write `Kodein.global.addImport(KodeinModule())` in the class that extends `Application` in order to get it to work.

The documentation is great - one of the best documented libraries I've used.
