### ISSUE TITLE
How to bind multiple interfaces to same singleton instance ?

### ISSUE THREAD

**Issue by monzou** [SalomonBrys/Kodein#85]
Hi, I'm trying to use Kodein for building web application.

After using Kodein for a while, I noticed that I don't know how to bind the **same singleton instance to multiple interfaces**. 

Here is an example.

```kotlin
interface Foo {
  fun foo(): String
}

interface Bar {
  fun bar(): String
}

class Baz(
  private val dependency1: Dependency1,
  private val dependency2: Dependency2,
  private val dependency3: Dependency3
): Foo, Bar {

  ...

}
```

How can I bind the same singleton instance (baz) to both foo and bar in such a case?

```kotlin
Kodein {

  bind<Foo> with singleton { Baz(instance(), instance(), instance()) }
  bind<Bar> with singleton { Baz(instance(), instance(), instance()) } // <-- This will instantiate different instance !

}
```

I would be pleased if you could give me an advice.
Thanks you for your awesome library !

**Comment by SalomonBrys** [comment]
Hi,
this is something that we sometimes do in our own application.
The trick is to actually bind the concrete class and then use that in the interface bindings.

Here's a code example based on your previous example:

```kotlin
Kodein {
  bind() from singleton { Baz(instance(), instance(), instance()) }
  bind<Foo> with provider { instance<Baz>() }
  bind<Bar> with provider { instance<Baz>() }
}
```

Note that `Foo` and `Bar` are bound as provider because they directly return the instance of `Baz` that is contains in it's own singleton. You could have them bound as singleton, but then you would then have 3 singelton containers, all containing the same instance, which is un-necessary.

Hope it helps ;)

**Comment by SalomonBrys** [comment]
Another trick would be to bind both instances with the same singleton binding:

```kotlin
val bazSingleton = singleton { Baz(instance(), instance(), instance()) }
bind<Foo> with bazSingleton
bind<Bar> with bazSingleton
```

This solution may be closer to what you are trying to achieve ;)

**Comment by monzou** [comment]
thank you for your quick reply ! very helpful ! 😃

**Comment by rocketraman** [comment]
@SalomonBrys This would be a good example to put in the docs.

**Comment by rocketraman** [comment]
A nice readable syntax for this uses `let` as follows:

```
singleton { Baz(instance(), instance(), instance()) }.let {
  bind<Foo> with it
  bind<Bar> with it
}
```
